server:
  port: 8124
  servlet:
    context-path: /api
spring:
  profiles:
    active: local
  application:
    name: casy-ai-code-mother
  mvc:
    async:
      request-timeout: 600000
  # context.initializer.classes 在 Spring Boot 3.4+ 已失效，请用 META-INF/spring.factories 或 main 中 addInitializers
  # 数据源配置
  datasource:
    # 驱动类名（可省略，SpringBoot 自动识别）
    driver-class-name: org.postgresql.Driver
    # 连接URL 固定格式：jdbc:postgresql://IP:端口/数据库名
    url: jdbc:postgresql://localhost:5432/casy_code
    username: postgres
    password: Hxb@93393
    # Hikari 连接池配置（生产环境推荐）
    hikari:
      minimum-idle: 5        # 最小空闲连接
      maximum-pool-size: 20  # 最大连接数
      idle-timeout: 300000   # 空闲超时时间
      max-lifetime: 1800000  # 连接最大生命周期
      connection-timeout: 20000 # 连接超时时间
  # JPA 专属配置（仅使用 JPA 时需要）
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL 方言
    hibernate:
      ddl-auto: update # 自动建表策略：update=自动更新表结构
    show-sql: true     # 控制台打印 SQL
    properties:
      hibernate.format_sql: true # 格式化 SQL


mybatis-flex:
  configuration:
    # 开启 数据库下划线 ↔ 实体类驼峰
    map-underscore-to-camel-case: true


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 1800
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.casy.casyaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# local的配置
#langchain4j:
#  open-ai:
#    streaming-chat-model:
#      base-url: https://api.deepseek.com
#      api-key: ${depAPI}
#      model-name: deepseek-v4-flash
#      max-tokens: 8192
#      strict-json-schema: true
#      response-format: json_object
#      log-requests: true
#      log-responses: true
#    chat-model:
#      base-url: https://api.deepseek.com
#      api-key: ${depAPI}
#      model-name: deepseek-v4-flash
#      max-tokens: 8192
#      strict-json-schema: true
#      response-format: json_object
#      log-requests: true
#      log-responses: true
#
#ai:
#  gpt:
#    base-url: http://gpttap.top/v1
#    api-key: ${NEWAPI}
#    model-name: gpt-5.5
#    max-tokens: 8192
#    strict-json-schema: true
#    response-format: json_object
#    log-requests: true
#    log-responses: true

