server:
  port: 8124
  servlet:
    context-path: /api
spring:
  profiles:
    active: local
  application:
    name: casy-ai-code-mother
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  mvc:
    async:
      request-timeout: 600000
  data:
    redis:
      host: 47.95.204.8
      port: 16379
      username: default
      password: YourStrongPassword123!
      database: 1
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/casy_code?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

mermaid:
  chrome-path: "C:/Program Files/Google/Chrome/Application/chrome.exe"

langchain4j:
  http-client:
    connect-timeout: 30s
    read-timeout: 600s
  ttl: 3600
  open-ai:
    chat-model:
      max-retries: 3

mybatis-flex:
  configuration:
    map-underscore-to-camel-case: true

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: 1800
  is-concurrent: false
  is-share: false
  token-style: uuid
  is-log: true

springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.casy.casyaicodemother.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
