worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

	# 静态资源服务器 - 80 端口
	server {
		listen       80;
		server_name  localhost;
		charset      utf-8;
		charset_types text/css application/javascript text/plain text/xml application/json;
		# 项目部署根目录
		root         D:/project/ideaProject/casy-ai-code-mother/tmp/code_deploy;
		
		# 处理所有请求
		# 配置中使用了 try_files 指令，能够按顺序尝试多个文件路径，从而更灵活地处理文件访问。举个例子，当访问 # # /app/style.css 时，会先尝试找到 /app/style.css 文件，如果不存在则返回 /app/index.html，最后才返回 404 # 错误，这样能够适配后续我们要生成的 Vue 单页面应用。

		# 💡 try_files 指令的具体解释：

		# /$1/$2：第一个尝试的路径
		# /$1/index.html：第二个尝试的路径
		# =404：如果都找不到，返回 404 错误
		
		# 访问URL			$1		$2			尝试路径1				尝试路径2
		# /app/				app		""			/app/				/app/index.html
		# /app/style.css	app		style.css	/app/style.css		/app/index.html
		# /app/js/main.js	app		js/main.js	/app/js/main.js		/app/index.html
		
		
		location ~ ^/([^/]+)/(.*)$ {
			try_files /$1/$2 /$1/index.html =404;
		}
	}
}
